name: Dump PNPM Dependencies

on:
  push:
    branches: [ 'package' ]
    paths:
      - 'package.json'
  workflow_dispatch:
  schedule:
    - cron: '0 0-23 * * *'
    - cron: '30 1-13 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18', '20', '22', '24' ]

    steps:
      - name: Decide whether to run the check
        id: chance
        run: echo "run=$([ $((RANDOM % 100)) -le 86 ] && echo true || echo false)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        if: steps.chance.outputs.run == 'true'
        with:
          ref: 'package'

      - name: Set up pnpm
        if: steps.chance.outputs.run == 'true'
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js ${{ matrix.node-version }}
        if: steps.chance.outputs.run == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        if: steps.chance.outputs.run == 'true'
        run: pnpm install --no-frozen-lockfile

      - name: Check whether the dependencies are normal
        if: steps.chance.outputs.run == 'true'
        run: pnpm update --latest